// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStreamContent(arg1) {
  return window['go']['main']['App']['GetStreamContent'](arg1);
}

export function LoadPrivateKey() {
  return window['go']['main']['App']['LoadPrivateKey']();
}

export function ProcessPcapFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessPcapFile'](arg1, arg2);
}

export function SelectPcapFile() {
  return window['go']['main']['App']['SelectPcapFile']();
}
