// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStreamContent(arg1:string):Promise<main.StreamData>;

export function LoadPrivateKey():Promise<string>;

export function ProcessPcapFile(arg1:string,arg2:Array<string>):Promise<main.PcapResult>;

export function SelectPcapFile():Promise<string>;
